name: "Error Report"
description: "File an error report"
title: "[ERROR]: "
labels: [ "bug" ]
assignees:
  - dumbdemon
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this error report!
  - type: dropdown
    id: command
    attributes:
      label: Command
      description: Which command were you attempting to run? If it wasn't a command, choose an "NAC" option.
      options:
        - about
        - check-perms
        - color-info
        - dad-jokes
        - dictionary
        - fibonacci
        - get-invite
        - kill
        - lmgtfy
        - meme
        - mtg-standard
        - ner
        - number-facts
        - ping
        - suggest-command
        - user-info
        - NAC/button
        - NAC/modal
        - NAC/User_Context
        - NAC/Message_Context
    validations:
      required: true
  - type: input
    id: date-time
    attributes:
      label: Date of Error
      description: When did this error occur? Include Timezone.
      placeholder: Ex. November 16, 2022 at 12:43 PM CST
    validations:
      required: true
  - type: textarea
    id: arguments
    attributes:
      label: Command Arguments
      description: Please list any and all arguments, buttons, modals, or context menus used to produce the error message.
      value: "None"
    validations:
      required: true
  - type: input
    id: discord-contact
    attributes:
      label: Discord Username
      description: If you need contact, type or paste your Discord username here. Expect a friend request from "Love And War II#5340".
      placeholder: Ex. Love And War II#5340
    validations:
      required: false
  - type: markdown
    attributes:
      value: "Thanks for filling this out! I'll get to this issue as soon as I can."