package com.terransky.TestingBot.slashSystem.cmdResources;

@SuppressWarnings("SpellCheckingInspection")
public class dadJokes {
    public String[] strings = {
            "I'm afraid for the calendar. Its days are numbered.",
            "My wife said I should do lunges to stay in shape.\n||That would be a big step forward!||",
            "Why do fathers take an extra pair of socks when they go golfing?\n\n||In case they get a hole in one!||",
            "Singing in the shower is fun until you get soap in your mouth.\n||Then it's a soap opera!||",
            "What do a tick and the Eiffel Tower have in common?\n\n||They're both Paris sites!||",
            "What do you call a fish wearing a bowtie?\n\n||So*fish*ticated!||",
            "How do you follow Will Smith in the snow?\n\n||You follow the fresh prints!||",
            "If April showers bring May flowers, what do May flowers bring?\n\n||Pilgrims!||",
            "I thought the dryer was shrinking my clothes. Turns out it was the refrigerator all along.",
            "What do you call a factory that makes okay products?\n\n||A satisfactory!||",
            "Dear Math, grow up and solve your own problems.",
            "What did the janitor say when he jumped out of the closet?\n\n||Supplies!||",
            "Have you heard about the chocolate record player?\n\n||It sounds pretty sweet!||",
            "What did the ocean say to the beach?\n\n||Nothing, it just waved!||",
            "Why do seagulls fly over the ocean?\n\n||Because if they flew over the bay, we'd call them bagels!||",
            "I only know 25 letters of the alphabet. I don't know y.",
            "How does the moon cut his hair?\n\n||Eclipse it!||",
            "What did one wall say to the other?\n\n||I'll meet you at the corner!||",
            "What did the zero say to the eight?\n\n||That belt looks good on you!||",
            "A skeleton walks into a bar and says, 'Hey, bartender. I'll have one beer and a mop.'",
            "Where do fruits go on vacation?\n\n||Pear-is!||",
            "I asked my dog what's two minus two. He said nothing.",
            "What did Baby Corn say to Mama Corn?\n\n||Where's Pop Corn?||",
            "What's the best thing about Switzerland?\n\n||I don't know, but the flag is a big plus!||",
            "What does a sprinter eat before a race?\n\n||Nothing, they fast!||",
            "Where do you learn to make a banana split?\n\n||Sundae school!||",
            "What has more letters than the alphabet?\n\n||The post office!||",
            "Dad, did you get a haircut?\n\n||No, I got them all cut!||",
            "What do you call a poor Santa Claus?\n\n||St. Nickel-less!||",
            "I got carded at a liquor store, and my Blockbuster card accidentally fell out. The cashier said never mind.",
            "Where do boats go when they're sick?\n\n||To the boat doc!||",
            "I don't trust those trees. They seem kind of shady.",
            "My wife is really mad at the fact that I have no sense of direction. So I packed up my stuff and right!",
            "How do you get a squirrel to like you?\n\n||Act like a nut.",
            "Why don't eggs tell jokes?\n\n||They'd crack each other up.",
            "I don't trust stairs. They're always up to something.",
            "What do you call someone with no body and no nose?\n\n||Nobody knows.",
            "Did you hear the rumor about butter?\n\n||Well, I'm not going to spread it!",
            "Why couldn't the bicycle stand up by itself?\n\n||It was two tired.",
            "What did one hat say to the other?\n\n||Stay here! I'm going on ahead!||",
            "Why did Billy get fired from the banana factory?\n\n||He kept throwing away the bent ones!||",
            "Dad, can you put my shoes on?\n\n||No, I don't think they'll fit me!||",
            "Why can't a nose be 12 inches long?\n\n||Because then it would be a foot!||",
            "What does a lemon say when it answers the phone?\n\n||Yellow!||",
            "This graveyard looks overcrowded. People must be dying to get in.",
            "What kind of car does an egg drive?\n\n||A yolkswagen!||",
            "Dad, can you put the cat out?\n\n||I didn't know it was on fire!||",
            "How do you make 7 even?\n\n||Take away the s!||",
            "How does a taco say grace?\n\n||Lettuce pray!||",
            "What time did the man go to the dentist?\n\n||Tooth hurt-y!||",
            "Why didn't the skeleton climb the mountain?\n\n||It didn't have the guts!||",
            "What do you call it when a snowman throws a tantrum?\n\n||A meltdown!||",
            "How many tickles does it take to make an octopus laugh?\n\n||Ten tickles!||",
            "I have a joke about chemistry, but I don't think it will get a reaction.",
            "What concert costs just 45 cents?\n\n||50 Cent featuring Nickelback!||",
            "What does a bee use to brush its hair?\n\n||A honeycomb!||",
            "How do you make a tissue dance?\n\n||You put a little boogie in it!||",
            "Why did the math book look so sad?\n\n||Because of all of its problems!||",
            "What do you call cheese that isn't yours?\n\n||Nacho cheese!||",
            "My dad told me a joke about boxing. I guess I missed the punch line.",
            "What kind of shoes do ninjas wear?\n\n||Sneakers!||",
            "How does a penguin build its house?\n\n||Igloos it together!||",
            "How did Harry Potter get down the hill?\n\n||Walking. JK! Rowling!||",
            "I used to be addicted to soap, but I'm clean now.",
            "A guy walks into a bar\u2026 and he was disqualified from the limbo contest.",
            "You think swimming with sharks is expensive?\n\n||Swimming with sharks cost me an arm and a leg!||",
            "When two vegans get in an argument, is it still called a beef?",
            "I ordered a chicken and an egg from Amazon. I'll let you know...",
            "Do you wanna box for your leftovers?\n\n||No, but I'll wrestle you for them!||",
            "That car looks nice but the muffler seems exhausted.",
            "Shout out to my fingers. I can count on all of them.",
            "If a child refuses to nap, are they guilty of resisting a rest?",
            "What country's capital is growing the fastest?\n\n||Ireland. Every day it's Dublin!||",
            "I once had a dream I was floating in an ocean of orange soda. It was more of a fanta sea.",
            "Did you know corduroy pillows are in style?\n\n||They're making headlines!||",
            "Did you hear about the kidnapping at school?\n\n||It's okay, he woke up!||",
            "A cheeseburger walks into a bar. The bartender says, *Sorry, we don't serve food here.*",
            "I once got fired from a canned juice company. Apparently I couldn't concentrate.",
            "I used to play piano by ear. Now I use my hands.",
            "Have you ever tried to catch a fog?\n\n||I tried yesterday but I mist!||",
            "I'm on a seafood diet. I see food and I eat it.",
            "Why did the scarecrow win an award?\n\n||Because he was outstanding in his field!||",
            "I made a pencil with two erasers. It was pointless.",
            "How do you make a Kleenex dance?\n\n||Put a little boogie in it!||",
            "I'm reading a book about anti-gravity. It's impossible to put down!",
            "Did you hear about the guy who invented the knock-knock joke?\n\n||He won the 'no-bell' prize!||",
            "I've got a great joke about construction, but I'm still working on it.",
            "I used to hate facial hair...but then it grew on me.",
            "I decided to sell my vacuum cleaner—it was just gathering dust!",
            "I had a neck brace fitted years ago and I've never looked back since.",
            "Why was 6 afraid of 7?\n\n||Because 7 was a registered 6 offender!||",
            "You know, people say they pick their nose, but I feel like I was just born with mine.",
            "What's brown and sticky?\n\n||A stick!||",
            "Why can't you hear a psychiatrist using the bathroom?\n\n||Because the 'P' is silent!||",
            "What do you call an elephant that doesn't matter?\n\n||An irrelephant!||",
            "What do you get from a pampered cow?\n\n||Spoiled milk!||",
            "I like telling Dad jokes. Sometimes he laughs!",
            "What's the best smelling insect?\n\n||A deodor-ant!||",
            "I used to be a personal trainer. Then I gave my too weak notice.",
            "Did I tell you the time I fell in love during a backflip?\n\n||I was heels over head!||",
            "If a child refuses to sleep during nap time, are they guilty of resisting a rest?",
            "I ordered a chicken and an egg online. I’ll let you know.",
            "It takes guts to be an organ donor.",
            "If you see a crime at an Apple Store, does that make you an iWitness?",
            "I'm so good at sleeping, I can do it with my eyes closed!",
            "I was going to tell a time-traveling joke, but you guys didn't like it.",
            "What do you call a fake noodle?\n\n||An impasta!||",
            "What do you call a belt made of watches?\n\n||A waist of time!||",
            "What happens when a strawberry gets run over crossing the street?\n\n||Traffic jam!||",
            "What do you call two monkeys that share an Amazon account?\n\n||Prime mates!||",
            "What do you call a pony with a sore throat?\n\n||A little hoarse!||",
            "Where do math teachers go on vacation?\n\n||Times Square!||",
            "Whenever I try to eat healthy, a chocolate bar looks at me and Snickers.",
            "What does garlic do when it gets hot?\n\n||It takes its cloves off!||",
            "What's a robot's favorite snack?\n\n||Computer chips!||",
            "How much does it cost Santa to park his sleigh?\n\n||Nothing, it's on the house!||",
            "Mountains aren't just funny. They're hill areas.",
            "What do clouds wear?\n\n||Thunderwear!||",
            "Why are piggy banks so wise?\n\n||They're filled with common cents!||",
            "Why is Peter Pan always flying?\n\n||He neverlands!||",
            "How do you get a good price on a sled?\n\n||You have toboggan!||",
            "How can you tell if a tree is a dogwood tree?\n\n||By its bark!||",
            "I used to hate facial hair, but then it grew on me.",
            "It's inappropriate to make a 'dad joke' if you're not a dad. It's a faux pa.",
            "What do you call a hot dog on wheels?\n\n||Fast food!||",
            "Where do young trees go to learn?\n\n||Elementree school!||",
            "Did you hear about the circus fire?\n\n||It was in tents!||",
            "Can February March?\n\n||No, but April May!||",
            "How do lawyers say goodbye?\n\n||We'll be suing ya!||",
            "Wanna hear a joke about paper?\n\n||Never mind—it's tearable!||",
            "What's the best way to watch a fly fishing tournament?\n\n||Live stream!||",
            "Spring is here! I got so excited I wet my plants.",
            "I could tell a joke about pizza, but it's a little cheesy.",
            "Don't trust atoms. They make up everything!",
            "When does a joke become a dad joke?\n\n||When it becomes apparent!||",
            "I wouldn't buy anything with velcro. It's a total rip-off.",
            "What’s an astronaut’s favorite part of a computer?\n\n||The space bar!||",
            "I don't play soccer because I enjoy the sport. I'm just doing it for kicks!",
            "Why are elevator jokes so classic and good?\n\n||They work on many levels!||",
            "Why do bees have sticky hair?\n\n||Because they use a honeycomb!||",
            "What do you call a fake noodle?\n\n||An impasta!||",
            "Which state has the most streets?\n\n||Rhode Island!||",
            "What did the coffee report to the police?\n\n||A mugging!||",
            "What did the fish say when he hit the wall?\n\n||Dam!||",
            "Is this pool safe for diving?\n\n||It deep ends!||",
            "If you see a crime happen at the Apple store, what does it make you?\n\n||An iWitness!||",
            "How many telemarketers does it take to change a light bulb?\n\n||Only one, but he has to do it while you are eating dinner!||",
            "How many narcissists does it take to screw in a light bulb?\n\n||One. The narcissist holds the light bulb while the rest of the world revolves around him!||",
            "How many DIY buffs does it take to change a light bulb?\n\n||One, but it takes two weeks and four trips to the hardware store!||",
            "How many paranoids does it take to change a light bulb?\n\n||Who wants to know?||",
            "I read that by law you must turn on your headlights when it’s raining in Sweden, but how am I supposed to know when it’s raining in Sweden?",
            "I was addicted to the hokey pokey\u2026 but I turned myself around.",
            "I don’t trust stairs. They are always up to something.",
            "Today, my son asked, *Can I have a bookmark?* I burst into tears—11 years old and he still doesn’t know my name is Brian.",
            " When I was a kid, my dad got fired from his job as a road worker for theft. I refused to believe he could do such a thing, but when I got home, the signs were all there.",
            "Why didn’t Han Solo enjoy his steak dinner?\n\n||It was Chewie!||",
            "Why don’t pirates take a bath before they walk the plank?\n\n||They just wash up on shore!||",
            "Why do you never see elephants hiding in trees?\n\n||Because they’re so good at it!||",
            "Did you hear about the racing snail who got rid of his shell?\n\n||He thought it would make him faster, but it just made him sluggish!||",
            "A turtle is crossing the road when he’s mugged by two snails. When the police ask him what happened, the shaken turtle replies, *I don’t know. It all happened so fast.*",
            "Did you hear about the guy who froze to death at the drive-in?\n\n||He went to see Closed for the Winter.",
            "We all know about Murphy’s Law: Anything that can go wrong will go wrong. But have you heard of Cole’s Law?\n\n||It’s thinly sliced cabbage!||",
            "When does a joke become a *dad joke*?\n\n||When it becomes apparent!||",
            "I had a happy childhood. My dad used to put me in tires and roll me down hills. Those were Goodyears.",
            "What invention allows us to see through walls?\n\n||Windows!||",
            "I know a bunch of good jokes about umbrellas, but they usually go over people’s heads.",
            "The bank keeps calling me to give me compliments. They say I have an *outstanding balance.*",
            "What is the most popular fish in the ocean?\n\n||A starfish!||",
            "Barbers…you have to take your hat off to them.",
            "What did one plate say to another plate?\n\n||Tonight, dinner’s on me!||",
            "Did you hear about the surgeon who enjoyed performing quick surgeries on insects?\n\n||He did one on the fly!||",
            " What’s a vampire’s favorite ship?\n\n||A blood vessel!||",
            "There’s only one thing I can’t deal with, and that’s a deck of cards glued together.",
            "The past, the present, and the future walked into a bar. It was tense.",
            "> Knock, knock.\n> Who’s there?\n> Nobel.\n> Nobel who?\n> No-bel, so I just knocked.",
            "> Knock, knock.\n> Who’s there?\n> Alabama.\n> Anybody with you?\n> Nope. I’m Alabama self.",
            "> Knock, knock.\n> Who’s there?\n> Ayatollah.\n> Ayatollah who?\n> Ayatollah you already.",
            "**Son**: Dad, I’m hungry.\n**Dad**: Hi hungry, I’m Dad.",
            "**Dad**: Did you hear about the kidnapping at school?\n**Son**: No. What happened?\n**Dad**: The teacher woke him up.",
            "**Daughter**: I have a lot of friends named Nathan. There’s Nathan Miller, Nathan Radcliff, Nathan Lewis\u2026\n**Me**: When they are together, do you call them the United Nathans?",
            "What’s the least-spoken language in the world?\n\n||Sign language!||",
            "What do you call a hippie’s wife?\n\n||Mississippi!||",
            "I searched for a lighter on Amazon, but all I could find were 6,000 matches.",
            "I sold our vacuum cleaner; it was just gathering dust.",
            "Did you hear about the crustacean accused of promoting his own shellfish interests?",
            "Did you hear about the bankrupt poet who ode everyone?",
            "Did you hear about the shepherd who drove his sheep through town and was given a ticket for making a ewe turn?",
            "Did you hear about the cat who ate a ball of yarn?\n\n||She had mittens!||",
            "Did you hear about the claustrophobic astronaut?\n\n||He just wanted a little more space!||",
            "What did the evil chicken lay?\n\n||Deviled eggs!||",
            "Did you hear they arrested the devil?\n\n||Yeah, they got him on possession!||",
            "A friend of mine didn’t pay his exorcist. He got repossessed.",
            "How do you make holy water?\n\n||You boil the hell out of it!||",
            "What sound does a witch’s car make?\n\n||Broom broom!||",
            "I want to go on record that I support farming. As a matter of fact, you could call me *protractor*.",
            "What’s the best way to watch a fly-fishing tournament?\n\n||Live stream!||",
            "How do you tell the difference between an alligator and a crocodile?\n\n||You will see one later and one in a while!||",
            "Why did the man name his dogs Rolex and Timex?\n\n||Because they were watchdogs!||",
            "What do you call a dog that can do magic?\n\n||A Labracabrador!||",
            "Why do dogs float in water?\n\n||Because they are good buoys!||",
            "What happens when it rains cats and dogs?\n\n||You have to be careful not to step in a poodle!||",
            "What do you call 50 pigs and 50 deer?\n\n||100 sows and bucks!||",
            "Why do cows wear bells?\n\n||Because their horns don’t work!||",
            "What do you call a fish with no eye?\n\n||A fsh!||",
            "Police arrested a bottle of water because it was wanted in three different states: solid, liquid, and gas.",
            "What do you call a lazy kangaroo?\n\n||Pouch potato!||",
            "Why is grass so dangerous?\n\n||Because it’s full of blades!||",
            "What is the Easter bunny’s favorite type of music?\n\n||Hip-hop!||",
            "A friend of mine is known for sweeping girls off their feet. He’s an extremely aggressive janitor.",
            "I’m an expert at picking leaves and heating them in water. It’s my special tea.",
            "My son’s fourth birthday was today. When he came to see me, I didn’t recognize him at first. I had never seen him be four.",
            "I recently went to the *World’s Tiniest Wind Turbine* exhibit. Honestly, not a big fan.",
            "I was out on a walk when I saw a sign that said, *Man wanted for robbery*. So I went in and applied for the job.",
            "How long should socks be?\n\n||Twelve inches, so you can fit in one foot!||",
            "Did you hear the joke about experiencing déjà vu?\n\n||Did you hear the joke about experiencing déjà vu?",
            "A bartender broke up with her boyfriend, but he kept asking her for another shot.",
            "I’m reading a novel where the main character has strained the muscles around his spine. That’s his back story.",
            "My doctor told me I’ve really grown as a person. Well, her exact words were that I *gained excess weight.*",
            " What do you call someone who always states the obvious?\n\n||Someone who always states the obvious!||",
            "Scientists have discovered what is believed to be the world’s largest bedsheet. More on this story as it unfolds.",
            "3.14 percent of sailors are pi-rates.",
            "You can’t plant flowers if you haven’t botany.",
            "What did the French chef give his wife for Valentine’s Day?\n\n||A hug and a quiche!||",
            "A ham sandwich walks into a bar and orders a beer. The bartender says, *Sorry, we don’t serve food here.*",
            "A couple of cups of yogurt walk into a country club. *We don’t serve your kind here,* the bartender says. *Why not?* one yogurt asks. *We’re cultured.*",
            "A brain walks into a bar and takes a seat. *I’d like some wings and a pint of beer, please,* it says. *Sorry, but I can’t serve you,* the bartender replies. *You’re out of your head.*",
            "A pirate walks into a bar with a paper towel on his head. The bartender says, *What’s with the paper towel?* The pirate says, *Arrr! I’ve got a Bounty on me head!*",
            "A guy walks into a bar, and there’s a horse serving drinks. The horse asks, *What are you staring at? Haven’t you ever seen a horse tending bar before?* The guy says, *It’s not that. I just never thought the parrot would sell the place.*",
            "Why did Beethoven get rid of his chickens?\n\n||All they said was, *Bach, Bach, Bach\u2026*||",
            "What did one DNA say to the other DNA?\n\n||*Do these genes make me look fat?*||",
            "What do you need to make a small fortune on Wall Street?\n\n||A large fortune!||",
            "How does the man in the moon get his hair cut?\n\n||Eclipse it!||",
            "Did you hear about the restaurant on the moon?\n\n||Great food, no atmosphere!||",
            "Did you hear the one about the kid who started a business tying shoelaces on the playground?\n\n||It was a knot-for-profit!||",
            "My kid wants to invent a pencil with an eraser on each end, but I just don’t see the point.",
            "Teacher: *There are two words I don’t allow in my class. One is gross, and the other is cool.*\nJohnny: *So, what are the words?*",
            "Why should you never mention the number 288?\n\n||It’s two gross!||",
            "I spent a lot of time, money, and effort childproofing my house, but the kids still get in.",
            "A cheese factory exploded in France. Da brie is everywhere!",
            "Did you hear the rumor about butter?\n\n||Well, I’m not going to spread it!",
            "Why do melons have weddings?\n\n||Because they cantaloupe.",
            "What do Bostonians call a fake noodle?\n\n||An impasta!||",
            "A college education now costs $100,000, but it produces three very proud people: the student, his mama, and his pauper.",
            "My son has his BA and his MA, but his P-A still supports him.",
            "What does a mobster buried in cement soon become?\n\n||A hardened criminal!||",
            "What does *idk* stand for?\n\n||Everyone I ask says, *I don’t know.*||",
            "Why was the pig covered in ink?\n\n||Because it lived in a pen!||",
            "Did you hear about the guy who stole 50 cartons of hand sanitizer?\n\n||They couldn’t prosecute—his hands were clean!||",
            "Why was the rookie police officer assigned to hunt the cannibal?\n\n||The more seasoned officers had already been eaten.",
            "What do you call a snitching scientist?\n\n||A lab rat!||",
            "What’s the difference between a man wearing pajamas on a bicycle and a guy wearing a tuxedo on a unicycle?\n\n||Attire!||",
            "It’s a shame that the Beatles didn’t make the submarine in that song green. That would’ve been sublime.",
            "Did you hear about the aquatic sea mammals that escaped from the zoo?\n\n||It was otter chaos!||",
            "What did the skeleton order with its beer?\n\n||A mop!||",
            "Why do nurses like red crayons?\n\n||Sometimes they have to draw blood!||",
            "How much do I love crunchy tacos?\n\n||From my head tomatoes!||",
            "What kind of spells do leprechauns use?\n\n||Lucky Charms!||",
            "What do you call a bear with no teeth?\n\n||A gummy bear!||",
            "My IQ test results came back. They were negative.",
            "What do you get when you cross a polar bear with a seal?\n\n||A polar bear!||",
            "Did you hear about the nurse who was chewed out by the doctor because she was absent without gauze?",
            "If athletes get athlete’s foot, what do astronauts get?\n\n||Missile toe!||",
            "My wife asked me to sync her phone, so I threw it into the ocean!||",
            "My wife is really mad that I have no sense of direction. I packed up my stuff and right.",
            "What did one cannibal say to the other while they were eating a clown?\n\n||Does this taste funny to you?",
            "Do I enjoy making courthouse puns?\n\n||Guilty!||",
            "What do you call someone with no body and no nose?\n\n||Nobody knows!||",
            "You know, people say they pick their nose, but I feel like I was just born with mine.",
            "In a freak accident today, a photographer was killed when a huge lump of cheddar landed on him. To be fair, the people who were being photographed did try to warn him.",
            "Can February March?\n\n||No, but April May!||",
            "Not sure if you have noticed, but I love bad puns. That’s just how eye roll.",
            "If you see a robbery at an Apple store, does that make you an iWitness?",
            "What did the drummer call his twin daughters?\n\n||Anna one, Anna two\u2026||",
            "What’s a bad wizard’s favorite computer program?\n\n||Spell check!||",
            "I was just reminiscing about the beautiful herb garden I had when I was growing up. Good thymes.",
            "I began to read a horror novel in braille. Something bad is about to happen—I can feel it.",
            "Why do pumpkins sit on porches?\n\n||They have no hands to knock on the door!||",
            "My friend wants to become an archaeologist, but I’m trying to put him off. I’m convinced his life will be in ruins.",
            " I got hit in the head with a can of Coke today. Don’t worry, I’m not hurt. It was a soft drink.",
            "Cooking out this weekend?\n\n||Don’t forget the pickle. It’s kind of a big dill!||",
            "Justice is a dish best served cold. If it were served warm, it would be just water.",
            "What’s orange and sounds like a parrot?\n\n||A carrot!||",
            "A steak pun is a rare medium done well.",
            "Why did the raisin go out with the prune?\n\n||Because he couldn’t find a date!||",
            "What’s brown and sticky?\n\n||A stick!||",
            "My dog accidentally swallowed a bunch of Scrabble tiles. I think this could spell disaster.",
            "I wondered why the ball was getting bigger. Then it hit me.",
            "I had a date last night. It was perfect. Tomorrow, I’ll try a grape.",
            "Armed robbers—some say they’re a drain on society, but you’ve got to give it to them.",
            "It hurts me to say this, but I have a sore throat.",
            "I know a surgeon who puts organs back in upside down. I told him that’s not funny, but he said it was an inside joke.",
            "My girlfriend says it’s either her or my career as a news reporter. I have some breaking news for her.",
            "Inflation is really getting out of hand, but that’s just my five cents.",
            "I can guess what people do for a living just by looking at their hands. I mean, I’m usually wrong, but I can guess.",
            "I’ve been breeding racing deer. Just trying to make a quick buck.",
            "How many mystery writers does it take to change a light bulb?\n\n||Two: One to screw it in most of the way and another to give it a surprise twist at the end!||",
            "My dentist offered me dentures for only a dollar. It sounded like a good deal at the time, but now I have buck teeth."
    };
}
